### ISSUE TITLE
Add support for Launchpad Mini

### ISSUE THREAD

**Issue by MarkDannemiller** [jreneew2/Launchpad-Controller#1]
Under the "FindAndRegisterLaunchpad()" in the Launchpad class, the check for "Launchpad" in the discovered midi controllers returns null for the LP Mini.  This can be fixed if the string "LPMini" is also included, since that's what Novation named it when searched for in the device manager.  The program works fine after that change, so if anyone has the same issue that's the fix that I found.  I haven't cloned this repo and created a pull request but I might get to that at some point when I work out all the kinks with the mini.  Great project this is coming in handy!

`public void FindAndRegisterLaunchpad()
        {
            for (int i = 0; i < InputDevice.InstalledDevices.Count; i++)
            {
                if (InputDevice.InstalledDevices[i].Name.Contains("LPMini"))
                {
                    Console.WriteLine("Found: " + InputDevice.InstalledDevices[i].Name);
                    launchpadInput = InputDevice.InstalledDevices[i];
                    launchpadInput.Open();
                }
            }

            for (int i = 0; i < OutputDevice.InstalledDevices.Count; i++)
            {
                if (OutputDevice.InstalledDevices[i].Name.Contains("LPMini"))
                {
                    Console.WriteLine("Found: " + OutputDevice.InstalledDevices[i].Name);
                    launchpadOutput = OutputDevice.InstalledDevices[i];
                    launchpadOutput.Open();
                }
            }`

**Comment by r4stered** [comment]
Yeah I can add that to the repo. Thanks for your contribution!
